site_name: Muruca Middleware Documentation
nav:
  - Home: index.md
  - About: about.md
  - Getting started: about.md
  - Documentation:
      - Introduction: it/interfaces/introduction.md
      - Interfaces:
        - Search: it/interfaces/search.md
        - Advanced search: it/interfaces/advancedSearch.md
  - Contact: contact.md
theme:
  name: material
  features:
    - navigation.tabs
  language: it
extra:
    alternate:
        - name: Italiano
          link: /it/ 
          lang: it
        - name: English
          link: /en/
          lang: en

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables

