site_name: Muruca Middleware Documentation
nav:
  - Home: index.md
  - About: about.md
  - Getting started: getting-started.md
  - Documentation:
      - Introduction: interfaces/introduction.md
      - Interfaces:
        - Search: interfaces/search.md
        - Advanced search: interfaces/advancedSearch.md
  - Contact: contact.md

theme:
  name: material
  features:
    - navigation.tabs
  language: it

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables

